### PR TITLE
feat: Introduce Langgraph Agent to KG query generation

### PR DESCRIPTION
**Pull request by fengsh27**
### Abstract
This submission introduced Langgraph Agent to KG query generation. Its graph is like the following image (generated by langgraph):
image

### Test
I tested it in genomicKB graph database, the result looks reasonable. Here is its logs for question "It’s odd for a transcription factor to be regulating both stemness of a cell and cytotoxic potential. Which of these is the primary function of EOMES and which is secondary?":
```
[info]2024-07-08T23:08:37.441672 - Answer: MATCH (g:gene {name: 'EOMES'})-[:regulate]->(c:gene) RETURN DISTINCT c.name LIMIT 5
[info]2024-07-08T23:08:37.441675 - Reflection | Improving: The query correctly identifies genes regulated by EOMES, which can help determine its primary and secondary functions based on the regulated genes' roles.
[info]2024-07-08T23:08:37.441678 - Reflection | Search Queries:
[info]2024-07-08T23:08:37.441683 - 1: MATCH (g:gene {name: 'EOMES'})-[:regulate]->(c:gene) RETURN DISTINCT c.name LIMIT 5
[info]2024-07-08T23:08:37.441687 - -------------------------------- Node Output --------------------------------
[info]2024-07-08T23:08:59.660204 - ## 2, execute_tool
[error]2024-07-08T23:08:59.660514 - content='{"query": "MATCH (g:gene {name: \'EOMES\'})-[:regulate]->(c:gene) RETURN DISTINCT c.name LI ...
[info]2024-07-08T23:10:32.454942 - ## 3, revise
[info]2024-07-08T23:10:32.454960 - Answer: MATCH (g:gene {name: 'EOMES'})-[:regulate]->(c:gene) RETURN DISTINCT c.name LIMIT 5
[info]2024-07-08T23:10:32.454967 - Reflection | Improving: The initial query returned no results. To improve the query, I will remove the relationship constraint and try to find any connections or properties related to EOMES that might indicate its primary and secondary functions.
[info]2024-07-08T23:10:32.454973 - Reflection | Search Queries:
[info]2024-07-08T23:10:32.454982 - 1: MATCH (g:gene {name: 'EOMES'})-[:regulate]->(c:gene) RETURN DISTINCT c.name LIMIT 5
[info]2024-07-08T23:10:32.454988 - Reflection | Revised Query:
[info]2024-07-08T23:10:32.454994 - MATCH (g:gene {name: 'EOMES'})-[]->(c) RETURN DISTINCT c.name, labels(c) LIMIT 5
[info]2024-07-08T23:10:32.454999 - -------------------------------- Node Output --------------------------------
[info]2024-07-08T23:13:46.213651 - ## 4, execute_tool
[error]2024-07-08T23:13:46.214115 - content='{"query": "MATCH (g:gene {name: \'EOMES\'})-[]->(c) RETURN DISTINCT c.name, labels(c) LIMIT ...
[info]2024-07-08T23:14:13.050621 - ## 5, revise
[info]2024-07-08T23:14:13.050637 - Answer: MATCH (g:gene {name: 'EOMES'})-[]->(c) RETURN DISTINCT c.name, labels(c) LIMIT 5
[info]2024-07-08T23:14:13.050642 - Reflection | Improving: The revised query returned some results, but they are not directly related to the primary and secondary functions of EOMES. To improve the query, I will focus on finding functional annotations or biological processes associated with EOMES.
[info]2024-07-08T23:14:13.050648 - Reflection | Search Queries:
[info]2024-07-08T23:14:13.050655 - 1: MATCH (g:gene {name: 'EOMES'})-[]->(c) RETURN DISTINCT c.name, labels(c) LIMIT 5
[info]2024-07-08T23:14:13.050662 - Reflection | Revised Query:
[info]2024-07-08T23:14:13.050667 - MATCH (g:gene {name: 'EOMES'})-[:involved_in]->(bp:biological_process) RETURN DISTINCT bp.name LIMIT 5
[info]2024-07-08T23:14:13.050671 - -------------------------------- Node Output --------------------------------
[error]2024-07-08T23:14:13.057490 - [HumanMessage(content='It’s odd for a transcription factor to be regulating both stemness of a cell  ...
[info]2024-07-08T23:14:13.058805 - 

-------------------------------- Final Generated Response --------------------------------
[info]2024-07-08T23:14:13.059458 - MATCH (g:gene {name: 'EOMES'})-[]->(c) RETURN DISTINCT c.name, labels(c) LIMIT 5
```

### CODE REVIEW

**Review by slobentanzer — COMMENTED** [review]
@fengsh27 looks good, can you please create some basic documentation of the usage and properties of the workflow?

**Comment by fengsh27** [comment]
Sure, I'll add some documentation.

**Comment by fengsh27** [comment]
@slobentanzer , I added documentation docs/reflexion-agent.md, please have a look

**Comment by slobentanzer** [comment]
@fengsh27 good start, thanks. I have extended it a little, but we need one more thing: the "usage" was more of an implementation description; good for developers but not actually an instruction of how to use the ReflexionAgent. Could you add a minimal example of how the KGQueryReflexionAgent would be used in an instance/workflow? Similar to the minimal examples we describe in the basic chat docs. Thanks!

**Comment by fengsh27** [comment]
Thanks for the revision, I'll add `usage` part.

**Comment by fengsh27** [comment]
@slobentanzer I've updated `Usage` in reflexion-agent.md, please have a look, and feel free to modify it. : )

**Review by slobentanzer — APPROVED** [review]
Great work, thanks. Just did some minor changes, but ready to merge now. :)

**Pull request merged**
